sudo: false
language: cpp
compiler: clang
script: 
  - make
  - ./wip-nameless-gaem
sources:
  - llvm-toolchain-precise-3.6
addons:
  apt:
    packages:
    - clang-3.6
    - libsfml-dev
    - libbox2d-dev
