language: cpp
sudo: false
dist: precise
compiler: clang
script: 
  - make CC=$COMPILER
  - ./wip-nameless-gaem
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - libsfml-dev
    - libbox2d-dev
env: COMPILER=clang++-3.9
