sudo: false
language: cpp
compiler: clang
script: 
  - make
  - ./wip-nameless-gaem
sources:
  - ubuntu-toolchain-r/test
  - llvm-toolchain-precise-3.9
addons:
  apt:
    packages:
    - clang-3.9
    - libsfml-dev
    - libbox2d-dev
